global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'bball_microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-gateway:8080', 'stats-service:8081', 'security-service:8082']