server:
  port: 8080  # The Gateway will be the entry point on port 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # Allows finding services automatically
          lower-case-service-id: true
      routes:
        # 1. Route to Security Service
        - id: security-service
          uri: lb://SECURITY-SERVICE  # 'lb' means Load Balanced via Eureka
          predicates:
            - Path=/api/v1/auth/** # Login/Register endpoints

        # 2. Route to Stats Service (Players & Watchlists)
        - id: stats-service
          uri: lb://STATS-SERVICE
          predicates:
            - Path=/api/players/**, /api/watchlists/**

        # 3. Route to Prediction Service
        - id: prediction-service
          uri: lb://PREDICTION-SERVICE
          predicates:
            - Path=/predict/**, /predictions/**, /model/**, /training/**, /cache/**

        # 4. Route to NBA Fetcher (Internal use mostly, but good for debugging)
        # We strip the prefix so /nba/player/LeBron -> NBA-FETCHER/player/LeBron
        - id: nba-fetcher
          uri: lb://NBA-FETCHER
          predicates:
            - Path=/nba/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: localhost

management:
  tracing:
    sampling:
      probability: 1.0 # Log 100% of requests for development
  zipkin:
    tracing:
      endpoint: "http://zipkin:9411/api/v2/spans"
  endpoints:
    web:
      exposure:
        include: health, info, prometheus # Enable the /prometheus endpoint
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true